sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "10"
  - "12"
  - "14"
  - "16"
env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4
  - WEBPACK_VERSION=5
install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION
script:
  - npm test
