sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "6"
  - "8"
  - stable
env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4
install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION
script:
  - npm test
